spring.application.name=gerenciadortarefas
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_tarefas
spring.datasource.username=nyxenn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
